const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('#main-nav');const glow=document.querySelector('.cursor-glow');
menuButton?.addEventListener('click',()=>{nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(nav.classList.contains('open')))});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>nav.classList.remove('open')));
if(window.matchMedia('(pointer:fine)').matches){document.addEventListener('pointermove',event=>{glow.style.transform=`translate(${event.clientX-90}px,${event.clientY-90}px)`})}
const sections=[...document.querySelectorAll('main section[id]')];const links=[...document.querySelectorAll('nav a[href^="#"]')];const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){links.forEach(link=>link.classList.toggle('current',link.getAttribute('href')===`#${entry.target.id}`))}})},{rootMargin:'-35% 0px -55% 0px'});sections.forEach(section=>observer.observe(section));
document.querySelectorAll('.project-card,.skills-grid article').forEach((card,index)=>{card.style.setProperty('--delay',`${index*60}ms`)});

const pageProgress=document.querySelector('.page-progress');const backTop=document.querySelector('.back-top');const cursorRing=document.querySelector('.cursor-ring');const cursorDot=document.querySelector('.cursor-dot');const tilt=document.querySelector('.tilt-card');
const revealItems=document.querySelectorAll('.section,.project-card,.skills-grid article,.contact-section');revealItems.forEach(item=>item.classList.add('reveal'));document.querySelectorAll('.reveal-group').forEach(item=>item.classList.add('reveal'));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});revealItems.forEach(item=>revealObserver.observe(item));
function updateScroll(){const max=document.documentElement.scrollHeight-window.innerHeight;pageProgress.style.width=`${max>0?(window.scrollY/max)*100:0}%`;backTop.classList.toggle('show',window.scrollY>650)}window.addEventListener('scroll',updateScroll,{passive:true});backTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));updateScroll();
if(window.matchMedia('(pointer:fine)').matches){document.addEventListener('pointermove',event=>{cursorRing.style.left=`${event.clientX}px`;cursorRing.style.top=`${event.clientY}px`;cursorDot.style.left=`${event.clientX}px`;cursorDot.style.top=`${event.clientY}px`});document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>{cursorRing.style.width='48px';cursorRing.style.height='48px';cursorRing.style.background='#e9633f22'});el.addEventListener('mouseleave',()=>{cursorRing.style.width='28px';cursorRing.style.height='28px';cursorRing.style.background='transparent'})});tilt?.addEventListener('pointermove',event=>{const rect=tilt.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width-.5;const y=(event.clientY-rect.top)/rect.height-.5;tilt.style.transform=`rotateX(${-y*7}deg) rotateY(${x*7}deg) rotate(4deg) scale(1.02)`});tilt?.addEventListener('pointerleave',()=>tilt.style.transform='rotate(4deg)')}
