from pathlib import Path

path = Path('/home/ubuntu/portif-lio/index.html')
html = path.read_text()
html = html.replace('O que estou <em>aprendendo.</em>', 'Ferramentas que já <em>uso e pratico.</em>')
html = html.replace('Uma caixa de ferramentas em expansão, feita de estudo, prática e muita curiosidade.', 'Uma base em desenvolvimento contínuo, construída em projetos web, mobile, banco de dados, prototipação e conteúdo digital.')
old = '<div class="tool"><i class="devicon-html5-plain colored"></i><strong>HTML</strong><small>Estrutura</small></div><div class="tool"><i class="devicon-css3-plain colored"></i><strong>CSS</strong><small>Estilo</small></div><div class="tool"><i class="devicon-javascript-plain colored"></i><strong>JavaScript</strong><small>Interação</small></div><div class="tool"><i class="devicon-react-original colored"></i><strong>React</strong><small>Interfaces</small></div><div class="tool"><i class="devicon-react-original colored"></i><strong>React Native</strong><small>Mobile</small></div><div class="tool"><i class="devicon-firebase-plain colored"></i><strong>Firebase</strong><small>Dados</small></div><div class="tool"><i class="devicon-php-plain colored"></i><strong>PHP</strong><small>Back-end</small></div><div class="tool"><i class="devicon-python-plain colored"></i><strong>Python</strong><small>Programação</small></div><div class="tool"><i class="devicon-arduino-plain colored"></i><strong>Arduino</strong><small>Eletrônica</small></div><div class="tool"><i class="devicon-git-plain colored"></i><strong>Git</strong><small>Versionamento</small></div>'
new = '<div class="tool"><i class="devicon-html5-plain colored"></i><strong>HTML5</strong><small>Estrutura semântica</small></div><div class="tool"><i class="devicon-css3-plain colored"></i><strong>CSS3</strong><small>Interfaces responsivas</small></div><div class="tool"><i class="devicon-javascript-plain colored"></i><strong>JavaScript</strong><small>Interação e lógica</small></div><div class="tool"><i class="devicon-react-original colored"></i><strong>React</strong><small>Componentes</small></div><div class="tool"><i class="devicon-react-original colored"></i><strong>React Native</strong><small>Experiências mobile</small></div><div class="tool"><i class="devicon-firebase-plain colored"></i><strong>Firebase</strong><small>Auth e Firestore</small></div><div class="tool"><i class="devicon-php-plain colored"></i><strong>PHP</strong><small>Desenvolvimento web</small></div><div class="tool"><i class="devicon-mysql-plain colored"></i><strong>SQL</strong><small>CRUD e dados</small></div><div class="tool"><i class="devicon-figma-plain colored"></i><strong>Figma</strong><small>UI e protótipos</small></div><div class="tool"><i class="devicon-git-plain colored"></i><strong>GitHub</strong><small>Versionamento</small></div>'
if old not in html:
    raise SystemExit('tools grid anchor not found')
html = html.replace(old, new, 1)
html = html.replace('Tenho conhecimentos em HTML, CSS, JavaScript, PHP, React, React Native, Firebase e SQL. Gosto de aprender fazendo: já desenvolvi projetos próprios e acadêmicos com autenticação, CRUD, banco de dados, interfaces responsivas e outras funcionalidades reais.', 'Tenho conhecimentos em HTML, CSS, JavaScript, PHP, React, React Native, Firebase e SQL intermediário. Também trabalho com Firebase Authentication, Firestore, GitHub, Vercel, Figma, Canva e Bootstrap. Gosto de aprender fazendo: já desenvolvi projetos próprios e acadêmicos com autenticação, CRUD, banco de dados, interfaces responsivas e outras funcionalidades reais.')
path.write_text(html)
print('Resume-based profile and stack updated')
